### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by CamilleDrapier** [xmppjs/xmpp.js#1038]
**Describe the bug**

After updating "@xmpp/resolve" from `0.13.1` to `0.13.3`, some import started failing.

**Logs**

```
    import http from 'node:http';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       8 | import _middleware from '@xmpp/middleware';
       9 | import _reconnect from '@xmpp/reconnect';
    > 10 | import _resolve from '@xmpp/resolve';
         | ^
      11 | import _resourceBinding from '@xmpp/resource-binding';
      12 | import _sasl from '@xmpp/sasl';
      13 | import plain from '@xmpp/sasl-plain';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1496:14)
      at Object.<anonymous> (node_modules/@xmpp/resolve/lib/http.js:4:35)
      at Object.<anonymous> (node_modules/@xmpp/resolve/resolve.js:4:14)
      at Object.<anonymous> (node_modules/@xmpp/resolve/index.js:3:17)
      at Object.<anonymous> (src/workers/comms/xmpp.ts:10:1)
      at Object.<anonymous> (src/workers/comms/worker.ts:4:1)
      at Object.<anonymous> (src/workers/comms/index.ts:10:1)
      at Object.<anonymous> (src/api/oauth.ts:8:1)
      at Object.<anonymous> (src/api/oauth.jest.spec.ts:3:1)
```

**Environment**

Operating System - Darwin(24.2.0) - darwin/arm64
NodeJs - 20.18.1
NPM - 10.8.2

Maybe it is a similar problem as to https://github.com/xmppjs/xmpp.js/issues/1031 ?

**Comment by CamilleDrapier** [comment]
Thanks for the feedback!

I looked a bit further into this and it seems, indeed, that [in version 13.3](https://github.com/xmppjs/xmpp.js/blob/v0.13.3/packages/resolve/resolve.js) there is no `import`, but the version of `node-fetch` was upgrade from 2.x to 3.x , and they state their [upgrade guide](https://github.com/node-fetch/node-fetch/blob/v3.3.2/docs/v3-UPGRADE-GUIDE.md#converted-to-es-module) that `require` cannot be used anymore.

In the [main // current version of resolve](https://github.com/xmppjs/xmpp.js/blob/main/packages/resolve/resolve.js), this is now an `import`, so the problem shouldn't be there anymore in the next release.
