### ISSUE TITLE
Reconnect option not working hostname ≠ servicename 

### ISSUE THREAD

**Issue by 9662** [xmppjs/xmpp.js#326]
``` javascript
var Client = require('node-xmpp-client');
var client = new Client({jid: "user@example.com/XYZ", password: "password", reconnect: true});
client.on('online', () => {console.log('online')});
client.on('connect', () => {console.log('connected')});
client.on('disconnect', e => console.log('disconnected', e));
```

If disconnected from the server, e.g., by kicking or a server restart or a resource conflict, etc., this results in:

```
connected
connected
online

disconnected { Error: has been kicked
// Blah blah
  stanza: 
   Stanza {
     name: 'stream:error',
     parent: null,
     children: [ [Object], [Object] ],
     attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' } } }
disconnected { Error: connect ECONNREFUSED 216.58.208.46:5222
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '216.58.208.46',
  port: 5222 }
disconnected { Error: connect ECONNREFUSED 216.58.208.46:5222
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '216.58.208.46',
  port: 5222 }
disconnected { Error: connect ECONNREFUSED 216.58.208.46:5222
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '216.58.208.46',
  port: 5222 }
// Etc., etc.
```

Now, if I do:

``` javascript
var client = new Client({jid: "user@example.com/XYZ", password: "password", host: "hostrunningxmpp.net", reconnect: true});
```

it works.

However, I believe this should also work without the `host` option, doing DNS SRV lookups as necessary.

**Comment by sonnyp** [comment]
nice find, I cannot work on this ATM, feel free to send a PR

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
