### ISSUE TITLE
C2S.TCPServer emits 'disconnect' event twice on client disconnection

### ISSUE THREAD

**Issue by smokku** [xmppjs/xmpp.js#393]
When C2S client disconnects (by sending `</stream:stream>`), the 'disconnect' event is emitted twice.

First:
```
Trace
    at Session.client.on.err (/home/smoku/devel/traffic/c2s.js:115:15)
    at emitNone (events.js:86:13)
    at Session.emit (events.js:185:7)
    at emitNone (events.js:91:20)
    at Connection.emit (events.js:185:7)
    at emitter.end.emitter.disconnect (/home/smoku/devel/traffic/node_modules/reconnect-core/index.js:108:15)
    at Connection.end.disconnect (/home/smoku/devel/traffic/node_modules/node-xmpp-core/lib/Connection.js:129:5)
    at StreamParser.<anonymous> (/home/smoku/devel/traffic/node_modules/node-xmpp-core/lib/Connection.js:241:12)
    at StreamParser.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at StreamParser.emit (events.js:185:7)
    at StreamParser.end (/home/smoku/devel/traffic/node_modules/node-xmpp-core/node_modules/@xmpp/streamparser/index.js:144:8)
    at SaxLtx.<anonymous> (/home/smoku/devel/traffic/node_modules/node-xmpp-core/node_modules/@xmpp/streamparser/index.js:62:12)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/home/smoku/devel/traffic/node_modules/ltx/lib/parsers/ltx.js:38:12)
    at SaxLtx.write (/home/smoku/devel/traffic/node_modules/ltx/lib/parsers/ltx.js:127:18)
    at StreamParser.write (/home/smoku/devel/traffic/node_modules/node-xmpp-core/node_modules/@xmpp/streamparser/index.js:134:17)
    at Connection.onData (/home/smoku/devel/traffic/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

Second:
```
Trace
    at Session.client.on.err (/home/smoku/devel/traffic/c2s.js:115:15)
    at emitOne (events.js:96:13)
    at Session.emit (events.js:188:7)
    at emitOne (events.js:101:20)
    at Connection.emit (events.js:188:7)
    at Socket.onDisconnect (/home/smoku/devel/traffic/node_modules/reconnect-core/index.js:59:17)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

When the client tears down connection, without ending the stream, only second emit happens.

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
