### ISSUE TITLE
Getting "SyntaxError: Unexpected token {" after a fresh installation of 0.2.0 release.

### ISSUE THREAD

**Issue by suhaibjanjua** [xmppjs/xmpp.js#460]
```
/home/ubuntu/messenger/node_modules/@xmpp/client/index.js:4
const {xml, jid} = require('@xmpp/client-core')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/AdamWithRainbow/node_modules/rainbow-node-sdk/lib/connection/XMPPService.js:13:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by sonnyp** [comment]
what is your node version? please use Node.js >= 6

**Comment by sonnyp** [comment]
engines node >= 6 added to the package.json files
