### ISSUE TITLE
Unable to connect to server which requires STARTTLS

### ISSUE THREAD

**Issue by DeanMarkTaylor** [xmppjs/xmpp.js#471]
When attempting to connect to `olark.com` I see a response which includes:
`policy-violation - Use of STARTTLS required`

Full output here:
```
🛈 connect
🛈 opening
⮊ <?xml version='1.0'?><stream:stream version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" to="olark.com">
⮈ <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='3132699445' from='olark.com' version='1.0' xml:lang='en'>
🛈 open <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" id="3132699445" from="olark.com" version="1.0" xml:lang="en"/>
⮈ <stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'><required/></starttls><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism></mechanisms><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='SmEOlxyl1VC3cDeOOVe6TSZbhHs='/></stream:features>
🛈 authenticate
AUTH
🛈 authenticating
⮊ <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">XXXXXXXXXXXXXXXXXXXXX=</auth>
⮈ <stream:error><policy-violation xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xml:lang='' xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Use of STARTTLS required</text></stream:error></stream:stream>
🛈 closing
❌ { StreamError: policy-violation - Use of STARTTLS required
    at XMPPError (c:\p1\node_modules\@xmpp\connection\index.js:10:5)
    at StreamError (c:\p1\node_modules\@xmpp\connection\index.js:20:5)
    at Parser.listeners.element.element (c:\p1\node_modules\@xmpp\connection\index.js:97:28)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.onEndElement (c:\p1\node_modules\@xmpp\xml\lib\Parser.js:54:12)
    at SaxLtx.Parser.parser.on.name (c:\p1\node_modules\@xmpp\xml\lib\Parser.js:33:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (c:\p1\node_modules\ltx\lib\parsers\ltx.js:38:12)
  name: 'StreamError',
  condition: 'policy-violation',
  text: 'Use of STARTTLS required',
  element:
   Element {
     name: 'stream:error',
     parent:
      Element {
        name: 'stream:stream',
        parent: null,
        children: [Object],
        attrs: [Object] },
     children: [ [Object], [Object] ],
     attrs: {} } }
❌ StreamError: policy-violation - Use of STARTTLS required
```

Making modifications to the following file makes it possible to connect:
https://github.com/xmppjs/xmpp.js/blob/master/packages/plugins/starttls/index.js

The modifications are shown here:
https://gist.github.com/DeanMarkTaylor/d9a326bb049f2db164a8423a4d16eb6a/revisions

I'm unsure of the exact impact of the changes on websocket connections and the commented issue https://prosody.im/issues/issue/837 as such didn't make a pull request.

**Comment by sonnyp** [comment]
@DeanMarkTaylor are you using xmpp.js master?

**Comment by DeanMarkTaylor** [comment]
Setup dev environment using:
```
npm i --save @xmpp/client
```
Which pulled `v0.2.0` according to `npm list`.

**Comment by sonnyp** [comment]
this was already fixed in https://github.com/xmppjs/xmpp.js/pull/449/files

I just published xmpp.js 0.3.0

Please confirm it works ok for you
