### ISSUE TITLE
unable to connect xmpp (ejabberd)

### ISSUE THREAD

**Issue by faysal515** [xmppjs/xmpp.js#494]
I took the basic example from docs and trying to connect my local machine

```
const {Client} = require('@xmpp/client')

const client = new Client()

client.start('xmpp://localhost:5222')
  .catch(e => console.log('.. ', e))

client.on('error', err => {
  console.error('------ ERROR ------- \n', err.toString())
})

client.on('status', (status, value) => {
  console.log('🛈', status, value ? value.toString() : '')
})

client.on('online', jid => {
  console.log('🗸', 'online as', jid.toString())
})

client.on('stanza', stanza => {
  console.log('⮈', stanza.toString())
})

client.handle('authenticate', authenticate => {
  return authenticate('user1@xyz', 'qweqwe')
})
```

I'm getting the following log/error

```
🛈 connect 
🛈 opening 
🛈 closing 
------ ERROR ------- 
 StreamError: host-unknown
🛈 close <stream:stream id="11717434128273588674" version="1.0" xml:lang="en" xmlns:stream="http://etherx.jabber.org/streams" from="127.0.0.1" xmlns="jabber:client"><stream:error><host-unknown xmlns="urn:ietf:params:xml:ns:xmpp-streams"/></stream:error></stream:stream>
🛈 open <stream:stream id="11717434128273588674" version="1.0" xml:lang="en" xmlns:stream="http://etherx.jabber.org/streams" from="127.0.0.1" xmlns="jabber:client"><stream:error><host-unknown xmlns="urn:ietf:params:xml:ns:xmpp-streams"/></stream:error></stream:stream>
..  { StreamError: host-unknown
    at XMPPError (/Users/faysal/development/sjxmpp/node_modules/@xmpp/connection/index.js:10:5)
    at StreamError (/Users/faysal/development/sjxmpp/node_modules/@xmpp/connection/index.js:20:5)
    at Parser.listeners.element.element (/Users/faysal/development/sjxmpp/node_modules/@xmpp/connection/index.js:107:11)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.onEndElement (/Users/faysal/development/sjxmpp/node_modules/@xmpp/connection-tcp/node_modules/@xmpp/xml/lib/Parser.js:54:12)
    at SaxLtx.Parser.parser.on.name (/Users/faysal/development/sjxmpp/node_modules/@xmpp/connection-tcp/node_modules/@xmpp/xml/lib/Parser.js:33:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/Users/faysal/development/sjxmpp/node_modules/ltx/lib/parsers/ltx.js:38:12)
  name: 'StreamError',
  condition: 'host-unknown',
  text: '',
  element: 
   Element {
     name: 'stream:error',
     parent: 
      Element {
        name: 'stream:stream',
        parent: null,
        children: [Object],
        attrs: [Object] },
     children: [ [Object] ],
     attrs: {} } }
🛈 disconnecting 
------ ERROR ------- 
 Error: read ECONNRESET
(node:1542) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: read ECONNRESET


```

**Comment by sonnyp** [comment]
please try

```js
client.start({uri: 'xmpp://localhost:5222', domain: 'xyz'})
  .catch(e => console.log('.. ', e))
```

**Comment by jsrhome** [comment]
I hit the same problem and spent a few hours before finding this post.  I would recommend you add this to your documentation, or better yet your example.js file.
