### ISSUE TITLE
Does this compatible with react native?

### ISSUE THREAD

**Issue by axcl** [xmppjs/xmpp.js#496]
Hi,
Anyone has luck of using this library with react native

**Comment by sonnyp** [comment]
Yes we use it with react native.

Check the crypho branch
https://github.com/xmppjs/xmpp.js/tree/crypho

**Comment by axcl** [comment]
Thanks i will check and update

**Comment by sid99** [comment]
@sonnyp I tried using the crypho branch with react native and I get 'document is not found' error.
Do you any sample code on using xmppjs with react native ?

**Comment by sid99** [comment]
@sonnyp I was able to integrate xmppjs with crypho branch but I get stream error unknown host

**Comment by sonnyp** [comment]
@sid99 can't help if you don't give details

Please provide your code to connect and the exact error

**Comment by sonnyp** [comment]
@sid99 can't help if you don't give details

Please provide your code to connect and the exact error

**Comment by sonnyp** [comment]
@sid99 can't help if you don't give details

Please provide your code to connect and the exact error

**Comment by sid99** [comment]
@sonnyp my bad
Here is the git repo link https://github.com/sid99/xmppjs-demo-app

steps followed:
1) started a new project using expo xde
2) yarn add xmpp.js
3) As I could not figure out how to pull the crypho branch, I updated the xmpp.js node module manually similar to the following commit https://github.com/xmppjs/xmpp.js/commit/9100a7110e2cc53f6df9bdad4871c87457c4e79d
4) Then I added the below line to App.js file
`
import { Client } from 'xmpp.js';
`

I now have the following error
`
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:656:19)
    at Object.readSync (/Users/sid/Documents/my_projects/react_native_apps/xmpss-demo-app/node_modules/graceful-fs/polyfills.js:138:28)
    at tryReadSync (fs.js:457:20)
    at Object.fs.readFileSync (fs.js:494:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Module._readSourceCode (/Users/sid/Documents/my_projects/react_native_apps/xmpss-demo-app/node_modules/metro-bundler/src/node-haste/Module.js:204:29)
    at Module._getCacheProps (/Users/sid/Documents/my_projects/react_native_apps/xmpss-demo-app/node_modules/metro-bundler/src/node-haste/Module.js:394:29)
    at Module._readFromTransformCache (/Users/sid/Documents/my_projects/react_native_apps/xmpss-demo-app/node_modules/metro-bundler/src/node-haste/Module.js:344:29)
    at Module.readCached (/Users/sid/Documents/my_projects/react_native_apps/xmpss-demo-app/node_modules/metro-bundler/src/node-haste/Module.js:331:19)
    at ResolutionRequest.preprocessModule (/Users/sid/Documents/my_projects/react_native_apps/xmpss-demo-app/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:324:27)
`

**Comment by sid99** [comment]
Update:
7) removed the document reference in getHostname function in connection/index.js module
8) this is when I got the "Stream error: unknown host" 
9) in getHostname function I used url-parse package to parse the uri 

So now I am able to connect the backend XMPP server! 

Let me know if there is a smoother way of integrating xmppjs with react native.

**Comment by axcl** [comment]
how to Add crypho branch with npm or yarn?

**Comment by axcl** [comment]
Hey @sid99 are you able to make it working cause i am not able to add it to my project.

**Comment by sid99** [comment]
@axcl I could not add crypho branch with npm or yarn, I manually updated the changes in the node_modules/xmppjs folder

**Comment by axcl** [comment]
@sid99 does this work for you cause i could not make it working on my side. 

Or are you using any other xmpp library cause?

**Comment by sid99** [comment]
I use expo sdk and following through the steps mentioned above, I was able to recreate the connection between the app and my xmpp server with xmppjs. I am not sure what your requirements are, for my requirements strophejs looks as a good solution and I am using that now. That library also required few tweaks.

**Comment by axcl** [comment]
@sid99 can you provide me documentation for using strophe it will be very helpful.

**Comment by sid99** [comment]
@axcl working on it will update in couple of days

**Comment by sonnyp** [comment]
master is now working with react-native
