### ISSUE TITLE
start failed. connection error at WebSocket.listeners.error.err (Socket.js:31)

### ISSUE THREAD

**Issue by SergeyChehuta** [xmppjs/xmpp.js#552]
I cannot connect to XMPP serve using WebSockets in a browser from ReactJS app or in the console.
Could you take a look and tell me what is wrong

after the fresh install, 
when I run the example from @xmpp/client:
` node example.js` 
works perfectly in the command line with address:
`client.start({uri: 'xmpp://jabber.hot-chilli.net:5222', domain:'jabber.hot-chilli.net'})`
but does not work in a browser (not supported transport)

if I change the address to:
`client.start({ uri: 'wss://jabber.hot-chilli.net:5281/xmpp-websocket', domain:'jabber.hot-chilli.net'})`

it does not connect in the command line:
```
connecting 
offline 
❌ Error: unexpected server response (403)
start failed { Error: unexpected server response (403)
    at ClientRequest._req.on (/Users/sergeychehuta/weconect/newest-xmpp/node_modules/ws/lib/WebSocket.js:653:21)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:539:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:444:20)
    at TLSSocket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onread (net.js:578:20)
  type: 'error',

```

and it does not connect in a browser.
Status Code: 403 Forbidden

```
index.js:2178 ❌ Error: connection error wss://jabber.hot-chilli.net:5281/xmpp-websocket
__stack_frame_overlay_proxy_console__ @ index.js:2178
(anonymous) @ App.js:35
./node_modules/events/events.js.EventEmitter.emit @ events.js:96
EventEmitter.(anonymous function) @ EventEmitter.js:46
listeners.error.error @ index.js:83
./node_modules/events/events.js.EventEmitter.emit @ events.js:96
listeners.error.err @ Socket.js:29
error (async)
_attachSocket @ Socket.js:41
connect @ Socket.js:15
Promise @ index.js:188
connect @ index.js:184
connect @ Client.js:38
connect @ index.js:74
start @ index.js:171
TryXMPP @ App.js:67
onClick @ App.js:16
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:461
executeDispatchesInOrder @ react-dom.development.js:483
executeDispatchesAndRelease @ react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
forEachAccumulated @ react-dom.development.js:562
runEventsInBatch @ react-dom.development.js:723
runExtractedEventsInBatch @ react-dom.development.js:732
handleTopLevel @ react-dom.development.js:4476
batchedUpdates$1 @ react-dom.development.js:16659
batchedUpdates @ react-dom.development.js:2131
dispatchEvent @ react-dom.development.js:4555
interactiveUpdates$1 @ react-dom.development.js:16714
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532
index.js:2178 start failed Error: connection error wss://jabber.hot-chilli.net:5281/xmpp-websocket
    at WebSocket.listeners.error.err (Socket.js:31)
__stack_frame_overlay_proxy_console__ @ index.js:2178
(anonymous) @ App.js:80
Promise.catch (async)
TryXMPP @ App.js:67
onClick @ App.js:16
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:461
executeDispatchesInOrder @ react-dom.development.js:483
executeDispatchesAndRelease @ react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
forEachAccumulated @ react-dom.development.js:562
runEventsInBatch @ react-dom.development.js:723
runExtractedEventsInBatch @ react-dom.development.js:732
handleTopLevel @ react-dom.development.js:4476
batchedUpdates$1 @ react-dom.development.js:16659
batchedUpdates @ react-dom.development.js:2131
dispatchEvent @ react-dom.development.js:4555
interactiveUpdates$1 @ react-dom.development.js:16714
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532
```

At the same time (after some dances) I can connect to the same server in ReactNative 
i.e. wss://jabber.hot-chilli.net:5281/xmpp-websocket

The source code (original example, only server URL is changed):
```

'use strict'

/* eslint-disable no-console */

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'

const {xml, Client} = require('./index') // For you; require('@xmpp/client')
const client = new Client()

// Log errors
client.on('error', err => {
  console.error('❌', err.toString())
})

// Log status changes
client.on('status', (status, value) => {
  console.log('🛈', status, value ? value.toString() : '')
})

// Useful for logging raw traffic
// Emitted for every incoming fragment
client.on('input', data => console.log('⮈', data))
// Emitted for every outgoing fragment
client.on('output', data => console.log('⮊', data))

// Useful for logging XML traffic
// Emitted for every incoming XML element
// client.on('element', data => console.log('⮈', data))
// Emitted for every outgoing XML element
// client.on('send', data => console.log('⮊', data))

client.on('stanza', el => {
  if (el.is('presence') && el.attrs.from === client.jid.toString()) {
    console.log('🗸', 'available, ready to receive <message/>s')
  }
})

client.on('online', jid => {
  console.log('jid', jid.toString())
  client.send(xml('presence'))
})

// "start" opens the socket and the XML stream
client
  //.start({uri: 'xmpp://jabber.hot-chilli.net:5222', domain:'jabber.hot-chilli.net'}) // TCP
  .start({ uri: 'wss://jabber.hot-chilli.net:5281/xmpp-websocket', domain:'jabber.hot-chilli.net'})
  .catch(err => {
    console.error('start failed', err)
  })

// Handle authentication to provide credentials
client.handle('authenticate', authenticate => {
  return authenticate('client', 'foobar')
})

// Handle binding to choose resource - optional
client.handle('bind', bind => {
  return bind('example')
})

process.on('unhandledRejection', (reason, p) => {
  console.log(
    'Possibly Unhandled Rejection at: Promise ',
    p,
    ' reason: ',
    reason
  )
})

```

**Comment by mathieuleddet** [comment]
@SergeyChehuta did you find a solution ?

**Comment by SergeyChehuta** [comment]
It did not work from reactJS for me, but from ReactNative it worked.
I guess that there could be  CORS issue - this server does not accept requests from other sites.

Sent from my iPhone

On 1 Nov 2018, at 20:29, mathieuleddet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @SergeyChehuta<https://github.com/SergeyChehuta>,

I'm using this service URI: wss://jabber.hot-chilli.net:443/xmpp-websocket .
I'm simply trying the sample of this page in a fresh react project :
https://github.com/xmppjs/xmpp.js/tree/master/packages/client

Thanks for your answer,
Mathieu

**Comment by mathieuleddet** [comment]
Thank you for your answer @SergeyChehuta -- I think you are right about CORS restriction on this server.

The Websocket handshake is made by the browser using an HTTP request: this is where CORS restriction apply and that's why we see 403 HTTP error code.
