### ISSUE TITLE
“TimeoutError”  when I start my client

### ISSUE THREAD

**Issue by GetHere** [xmppjs/xmpp.js#570]
```
@xmpp/client: v0.5.0   
yarn : v1.10.1
node: v10.1.0
npm： v5.6.0
```
### install
I installed @xmpp/client via yarn
` yarn add @xmpp/client  `

### usage
```
      const user = 'zxy';
      const psw = 'psw';
      
      process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

      const {client, xml, jid} = require('@xmpp/client')

      const xmpp = client({
        service: 'xmpp://10.254.2.11:5222',
        // domain: '10.254.2.11',
        resource: 'PC-12334234hiasdhasgasd',
        username: user,
        password: psw,
      })

      xmpp.on('error', err => {
        console.error('❌', err.toString())
      })

      xmpp.on('offline', () => {
        console.log('🛈', 'offline')
      })

      xmpp.on('online', async address => {
        console.log('🗸', 'online as', address.toString())

        // Sends a chat message to itself
        const message = xml(
          'message',
          {type: 'chat', to: address},
          xml('body', 'hello world')
        )
        xmpp.send(message)
      })

      xmpp.on('stanza', stanza => {
        console.log('⮈', stanza.toString())
        // xmpp.stop()
      })

      xmpp.on('status', (status, value) => {
        console.log('status:', status, value ? value.toString() : '')
      })

      xmpp.start().catch(err=>{
        console.log(err)
      })
```

### log
I think what I did  entirely based on the document. However, It always  gone wrong when starting. 
and then there is log.
```
status: connect 

status: opening 

status: opening 

status: opening

⮈ <iq type="result" id="2pozpzqyzah" to="sunrunvas/55mwesr48c"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>zxy/PC-12334234hiasdhasgasd</jid></bind></iq>

status: online zxy/PC-12334234hiasdhasgasd

🗸 online as zxy/PC-12334234hiasdhasgasd

⮈ <message id="6fdb123df7494ba7a57fc663543c87f8" from="zxy/PC-12334234hiasdhasgasd" to="zxy/PC-12334234hiasdhasgasd"><received xmlns="urn:xmpp:receipts"/></message>

//there is errinfo
TimeoutError
    at Promise.race.delay.then (F:\file\scloud\im-test\node_modules\@xmpp\events\lib\timeout.js:10:13)
    at <anonymous>

❌ TimeoutError

//however I could chat with other continuously
status: online zxy/PC-12334234hiasdhasgasd

🗸 online as zxy/PC-12334234hiasdhasgasd
```
 I don't konw why It alawys reported error. Please tell me how can I avoid the mistake?

**Comment by GetHere** [comment]
by the way , I used v0.3.0 without error last week.

**Comment by sonnyp** [comment]
@GetHere can you add the following and copy paste the output

```js
const debug = require('@xmpp/debug')
...
debug(xmpp, true)
```

and copy paste the result, also what server/version are you using?

**Comment by GetHere** [comment]
It's so sad that log was no chance after I added those codes.

**Comment by GetHere** [comment]
and  my server:
```
openfire:  v4.2.3
```

**Comment by sonnyp** [comment]
> It's so sad that log was no chance after I added those codes.

?

**Comment by lacivert** [comment]
I have the same problem. 
Afterall it is still online. I am not sure if this is somehting about xmppjs or a real error about server-client connection.

Here is the debug;

```
🛈 connecting 
🛈 connect 
🛈 opening 
⮊ <?xml version='1.0'?><stream:stream version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" to="172.16.7.4">
⮈ <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="myserver.net" id="ccf0e833" xml:lang="en" version="1.0">
⮈ <stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism></mechanisms><auth xmlns="http://jabber.org/features/iq-auth"/><register xmlns="http://jabber.org/features/iq-register"></stream:features>
⮊ <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">somebase64encodedstring</auth>
⮈ <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>
🛈 opening 
⮊ <?xml version='1.0'?><stream:stream version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" to="172.16.7.4">
⮈ <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="myserver.net" id="ccf0e833" xml:lang="en" version="1.0"><stream:features>bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features>
⮊ <iq type="set" id="bp9mxcbzurl" xmlns="jabber:client"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>myclient</resource></bind></iq>
⮈ <iq type="result" id="bp9mxcbzurl" to="myserver.net/ccf0e833"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>4805@myserver.net/myclient</jid></bind></iq>
🛈 online 4805@myserver.net/myclient
⮊ <iq type="set" id="g9sqzzbmg6j" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq>
⮊ <presence xmlns="jabber:client"/>
⮈ <iq type="result" id="g9sqzzbmg6j" to="4805@myserver.net/myclient"/>
⮈ <presence id="M9E2P-7" from="finesse@myserver.net/web_framework" to="4805@myserver.net/myclient"/>
(node:47364) UnhandledPromiseRejectionWarning: TimeoutError
    at Promise.race.delay.then (/path/to/project/node_modules/@xmpp/events/lib/timeout.js:10:13)
(node:47364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
❌ { TimeoutError
    at Promise.race.delay.then (/path/to/project/node_modules/@xmpp/events/lib/timeout.js:10:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
TimeoutError
    at Promise.race.delay.then (/path/to/project/node_modules/@xmpp/events/lib/timeout.js:10:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
