### ISSUE TITLE
TimeoutError on starting client

### ISSUE THREAD

**Issue by lacivert** [xmppjs/xmpp.js#592]
Same issue as #570 (without yarn)

```
@xmpp/client: v0.5.2
node: v10.13.0
npm： v6.4.1
```

My os is Mac os x but same thing happening on Ubuntu 14 and same node/npm versions.

TimeoutError on starting client.
Afterall it is still online. I am not sure if this is somehting about xmppjs or a real error about server-client connection.

Here is the debug;

```
🛈 connecting 
🛈 connect 
🛈 opening 
⮊ <?xml version='1.0'?><stream:stream version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" to="172.16.7.4">
⮈ <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="myserver.net" id="ccf0e833" xml:lang="en" version="1.0">
⮈ <stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism></mechanisms><auth xmlns="http://jabber.org/features/iq-auth"/><register xmlns="http://jabber.org/features/iq-register"></stream:features>
⮊ <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">somebase64encodedstring</auth>
⮈ <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>
🛈 opening 
⮊ <?xml version='1.0'?><stream:stream version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" to="172.16.7.4">
⮈ <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="myserver.net" id="ccf0e833" xml:lang="en" version="1.0"><stream:features>bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features>
⮊ <iq type="set" id="bp9mxcbzurl" xmlns="jabber:client"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>myclient</resource></bind></iq>
⮈ <iq type="result" id="bp9mxcbzurl" to="myserver.net/ccf0e833"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>4805@myserver.net/myclient</jid></bind></iq>
🛈 online 4805@myserver.net/myclient
⮊ <iq type="set" id="g9sqzzbmg6j" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq>
⮊ <presence xmlns="jabber:client"/>
⮈ <iq type="result" id="g9sqzzbmg6j" to="4805@myserver.net/myclient"/>
⮈ <presence id="M9E2P-7" from="finesse@myserver.net/web_framework" to="4805@myserver.net/myclient"/>
(node:47364) UnhandledPromiseRejectionWarning: TimeoutError
    at Promise.race.delay.then (/path/to/project/node_modules/@xmpp/events/lib/timeout.js:10:13)
(node:47364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
❌ { TimeoutError
    at Promise.race.delay.then (/path/to/project/node_modules/@xmpp/events/lib/timeout.js:10:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
TimeoutError
    at Promise.race.delay.then (/path/to/project/node_modules/@xmpp/events/lib/timeout.js:10:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

_Originally posted by @lacivert in https://github.com/xmppjs/xmpp.js/issues/570#issuecomment-438685731_

**Comment by lacivert** [comment]
I think it is about IP/hostname difference. This timeout error happens when the domain option is an IP address (like '172.16.7.4'). But when I put it as 'myserver.net', it works without timeout error.

**Comment by sonnyp** [comment]
@lacivert thanks for the bug report, can you help me debugging this further:

* what server/version are you using?
* why are you using an ip address as domain?

**Comment by lacivert** [comment]
This is like an intranet solution and sometimes the xmpp servers information are not known; like domain/hostname etc. But generally it is [Cisco Jabber](https://www.cisco.com/c/en/us/about/corporate-strategy-office/acquisitions/jabberinc.html)

**Comment by sonnyp** [comment]
fixed in `0.6.1`

**Comment by darioxtx** [comment]
Hi,

Using version ```0.6.1``` and configuration bellow I'm not able to connect to chat server any more. It just hangs with no explanation.

```javascript
const xmpp = client({
  service: 'ws://example.com:7070/ws',
  domain: 'localhost',
  resource: 'node',
  username: 'admin',
  password: 'xxx',
})
```

Using ```0.5.2``` I'm able to connect to chat server but I'm getting same ```TimeoutError```. I can't use latest version because I'm unable to connect anymore.

Thanks

**Comment by lacivert** [comment]
> fixed in 0.6.0 :) https://github.com/xmppjs/xmpp.js/releases/tag/v0.6.0
> 
> please confirm and close

I confirm, it is working without a problem for my side. Thank you very much

**Comment by darioxtx** [comment]
Using **websocket** connection client is not connecting to server. I tried `0.6.0`, `0.6.1` and `0.6.2`. This issue should be reopened.

Thanks

**Comment by sonnyp** [comment]
@darioxtx Node.js v10 is the official minimum supported version.

**Comment by darioxtx** [comment]
Thanks

**Comment by vipinnegi90** [comment]
How do I check this xmpp/client version on my openfire setup in a ubuntu server and how do I update it? Sorry I am new into this.
