### ISSUE TITLE
ReferenceError: debug is not defined

### ISSUE THREAD

**Issue by timepp** [xmppjs/xmpp.js#814]
using exactly the example in the npm page resule the following error
---
```
D:\xmpptest>node ./main.js
D:\xmpptest\main.js:11
debug(xmpp, true)
^

ReferenceError: debug is not defined
    at Object.<anonymous> (D:\xmpptest\main.js:11:1)
[90m    at Module._compile (internal/modules/cjs/loader.js:1144:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:993:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:892:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

D:\xmpptest>node -v
v13.6.0
```

**Comment by sonnyp** [comment]
I will fix the README, meanwhile:

install `@xmpp/debug`

and 

`const debug = require('@xmpp/debug')`

**Comment by timepp** [comment]
Thanks!

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/pull/816
