### ISSUE TITLE
null parser on stop()

### ISSUE THREAD

**Issue by andreas-ibm** [xmppjs/xmpp.js#860]
Hello!

I'm not sure what happened to lead up to this, but my program died out because of:
```
TypeError: Cannot read property 'write' of null
    at Client._onData (/path/to/node_modules/@xmpp/connection/index.js:50:17)
    at TLSSocket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

I've been trying to debug some other problems with connecting to OpenFire, but this one came out of the blue and killed the program. Looking at the OpenFire log around the same time it looks like it's considering a connection "IDLE" around the same time, could be related?

**Comment by sonnyp** [comment]
So you called `stop()` and you got `TypeError: Cannot read property 'write' of null` ?

What is your version of xmpp.js ?

What environment / version?

**Comment by harleenarora** [comment]
same issue 
versions: 
"@xmpp/client": "^0.13.1",
"@xmpp/debug": "^0.13.0",
"react-native": "^0.70.5",
