### ISSUE TITLE
bad-namespace-prefix

### ISSUE THREAD

**Issue by silverbucket** [xmppjs/xmpp.js#957]
**Describe the bug**
Recently started seeing this exception raised without any context on what may have caused it:
```
StreamError: bad-namespace-prefix
    at Function.fromElement (/Users/njenning/code/projects/sockethub/packages/platform-xmpp/node_modules/@xmpp/error/index.js:29:19)
    at Client._onStreamError (/Users/njenning/code/projects/sockethub/packages/platform-xmpp/node_modules/@xmpp/connection/index.js:116:31)
    at Client._onElement (/Users/njenning/code/projects/sockethub/packages/platform-xmpp/node_modules/@xmpp/connection/index.js:101:12)
    at Parser.emit (node:events:394:28)
    at Parser.onEndElement (/Users/njenning/code/projects/sockethub/packages/platform-xmpp/node_modules/@xmpp/xml/lib/Parser.js:52:12)
    at SaxLtx.emit (node:events:394:28)
    at SaxLtx._handleTagOpening (/Users/njenning/code/projects/sockethub/packages/platform-xmpp/node_modules/ltx/lib/parsers/ltx.js:44:14)
    at SaxLtx.write (/Users/njenning/code/projects/sockethub/packages/platform-xmpp/node_modules/ltx/lib/parsers/ltx.js:192:20)
    at Parser.write (/Users/njenning/code/projects/sockethub/packages/platform-xmpp/node_modules/@xmpp/xml/lib/Parser.js:71:17)
    at Client._onData (/Users/njenning/code/projects/sockethub/packages/platform-xmpp/node_modules/@xmpp/connection/index.js:49:17)
```

**Logs**
I don't have any at the moment, but will try enabling this and waiting for the problem to occur again
https://github.com/xmppjs/xmpp.js/tree/main/packages/debug

**Environment**
Running in node.js 16

**Comment by silverbucket** [comment]
Even with debugging enabled, I don't get any additional information, the stack trace just appears without any other output.

**Comment by sonnyp** [comment]
Please share the logs - even if you don't see anything familiar in them.

What XMPP server/version ?
