### ISSUE TITLE
Does not reconnect when disconnect isn't clean

### ISSUE THREAD

**Issue by realtux** [xmppjs/xmpp.js#993]
⚠ If you need help with XMPP itself, please visit https://xmpp.org/community/ instead.

**Describe the bug**
Reconnection works great when the connection is severed cleanly, such as when a client is disconnected remotely. However, when doing something like pulling an ethernet cable or disconnecting from wifi, the client will just hang forever. I've seen this issue on similar tools, where the issue is the keepalive mechanism is either not performing correctly or is configured incorrectly.

**Logs**
No logs, client hangs and outputs nothing until manually restarted.

**Environment**
Xubuntu, Node.js 18, latest xmpp.js.

**Comment by realtux** [comment]
Updated information:
Only doesn't reconnect when using xmpps:// schema on port 5223. xmpp:// on 5222 works fine.

**Comment by raucao** [comment]
I just stumbled upon the same issue.

After I couldn't find an easy fix, I started implementing pings in my program, but halfway I through thought it was a bit silly patching over this from the outside, when the goal of the library is to not manage connections manually. I think it should be treated as a bug, because loosing connectivity for any reason whatsoever should eventually result in an automatic reconnect.

**Comment by raucao** [comment]
You can just disconnect your Internet (e.g. turn off wifi) while any program using the latest npm module is running.

**Comment by realtux** [comment]
external ping is how i ultimately solved this, but it doesn't feel like something that a user should have to do, since reconnect logic does exist already, just not for the xmpps scheme. i spent some time looking at the code base to propose a fix, but i'm just not familiar with it so i had a hard time locating where the tcp logic is. i'll continue to investigate.

**Comment by ilya-lopukhin** [comment]
the library is very buggy currently without the connection present. The ENOTFOUND internal xmppjs error is missing the proper on('error') handler, propagating to the bottommost unhandledrejection handler and crashing the whole node process around it in case the connection ended abruptly

**Comment by raucao** [comment]
I wanted to verify the fix, but failed to load the client dependency directly from GitHub.

What's the recommended way for running custom versions of this monorepo's packages, that are not published on npm?

**Comment by raucao** [comment]
I think I already found a bug. Running this with the plain client example code (with the disconnect removed), results in this error after about 10 seconds or so:

```
IN
<r xmlns="urn:xmpp:sm:3"/>
OUT
<a xmlns="urn:xmpp:sm:3" h="2"/>
OUT
<r xmlns="urn:xmpp:sm:3"/>
IN
<a h="1" xmlns="urn:xmpp:sm:3"/>
TypeError: Cannot read properties of undefined (reading 'stanza')
    at ackQueue (file:///home/basti/src/xmpp.js/packages/stream-management/index.js:88:27)
    at file:///home/basti/src/xmpp.js/packages/stream-management/index.js:134:7
    at dispatch (/home/basti/src/xmpp.js/node_modules/koa-compose/index.js:42:32)
    at file:///home/basti/src/xmpp.js/packages/stream-features/index.js:13:16
    at dispatch (/home/basti/src/xmpp.js/node_modules/koa-compose/index.js:42:32)
    at file:///home/basti/src/xmpp.js/packages/stream-features/index.js:13:16
    at dispatch (/home/basti/src/xmpp.js/node_modules/koa-compose/index.js:42:32)
    at file:///home/basti/src/xmpp.js/packages/stream-features/index.js:13:16
    at dispatch (/home/basti/src/xmpp.js/node_modules/koa-compose/index.js:42:32)
    at iqHandler (file:///home/basti/src/xmpp.js/packages/iq/callee.js:59:31)
TypeError: Cannot read properties of undefined (reading 'stanza')
    at ackQueue (file:///home/basti/src/xmpp.js/packages/stream-management/index.js:88:27)
    at file:///home/basti/src/xmpp.js/packages/stream-management/index.js:134:7
    at dispatch (/home/basti/src/xmpp.js/node_modules/koa-compose/index.js:42:32)
    at file:///home/basti/src/xmpp.js/packages/stream-features/index.js:13:16
    at dispatch (/home/basti/src/xmpp.js/node_modules/koa-compose/index.js:42:32)
    at file:///home/basti/src/xmpp.js/packages/stream-features/index.js:13:16
    at dispatch (/home/basti/src/xmpp.js/node_modules/koa-compose/index.js:42:32)
    at file:///home/basti/src/xmpp.js/packages/stream-features/index.js:13:16
    at dispatch (/home/basti/src/xmpp.js/node_modules/koa-compose/index.js:42:32)
    at iqHandler (file:///home/basti/src/xmpp.js/packages/iq/callee.js:59:31)
```

**Comment by raucao** [comment]
OK, so when I shut off my Internet, I can see the OUT messages for stream management, but it never sets the status to offline, and thus never seems to try to reconnect:

```
OUT
<r xmlns="urn:xmpp:sm:3"/>
OUT
<r xmlns="urn:xmpp:sm:3"/>
OUT
<r xmlns="urn:xmpp:sm:3"/>
OUT
<r xmlns="urn:xmpp:sm:3"/>
```

**Comment by raucao** [comment]
@sonnyp Wondering if you ever saw my last two replies here?

**Comment by sonnyp** [comment]
@raucao  please file a new issue https://github.com/xmppjs/xmpp.js/issues/new?template=bug-report.md

**Comment by raucao** [comment]
But it's the same issue. Nothing has changed since the original issue description.

**Comment by sonnyp** [comment]
Yes things have changed. File a new issue with logs and a reproducer.

**Comment by raucao** [comment]
So you definitely cannot reproduce the issue that was originally documented with the information from https://github.com/xmppjs/xmpp.js/issues/993#issuecomment-2612907364 and https://github.com/xmppjs/xmpp.js/issues/993#issuecomment-2612918724 then, correct?
